using Microsoft.EntityFrameworkCore.Migrations;

namespace Shb.Infrastructure.Migrations
{
    public partial class ShbInit : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Shb");

            migrationBuilder.CreateTable(
                name: "Superheroes",
                schema: "Shb",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Attack = table.Column<int>(nullable: false),
                    Defence = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Superheroes", x => x.Id);
                });

            migrationBuilder.InsertData(
                schema: "Shb",
                table: "Superheroes",
                columns: new[] { "Id", "Attack", "Defence", "Name" },
                values: new object[,]
                {
                    { 1, 0, 0, "Customer Marketing Officer" },
                    { 204, 7, 7, "Customer Communications Consultant" },
                    { 203, 1, 6, "Lead Functionality Director" },
                    { 202, 10, 8, "Global Tactics Administrator" },
                    { 201, 2, 6, "Human Functionality Engineer" },
                    { 200, 6, 0, "Product Branding Officer" },
                    { 199, 0, 10, "Human Accounts Engineer" },
                    { 205, 1, 4, "Dynamic Assurance Planner" },
                    { 198, 3, 4, "Lead Tactics Coordinator" },
                    { 196, 1, 0, "Global Communications Producer" },
                    { 195, 8, 0, "Forward Interactions Assistant" },
                    { 194, 1, 7, "Future Intranet Associate" },
                    { 193, 3, 5, "International Functionality Officer" },
                    { 192, 10, 1, "District Usability Facilitator" },
                    { 191, 0, 9, "Customer Program Representative" },
                    { 197, 0, 2, "Dynamic Solutions Officer" },
                    { 206, 10, 7, "Senior Paradigm Analyst" },
                    { 207, 6, 6, "National Communications Executive" },
                    { 208, 2, 1, "Forward Accountability Manager" },
                    { 223, 5, 10, "Customer Markets Strategist" },
                    { 222, 8, 2, "Corporate Infrastructure Director" },
                    { 221, 6, 10, "Lead Implementation Liaison" },
                    { 220, 3, 5, "Chief Marketing Technician" },
                    { 219, 3, 5, "Regional Brand Analyst" },
                    { 218, 7, 9, "Corporate Operations Representative" },
                    { 217, 8, 9, "Corporate Brand Planner" },
                    { 216, 4, 3, "Global Assurance Assistant" },
                    { 215, 3, 4, "Global Solutions Strategist" },
                    { 214, 9, 10, "District Brand Manager" },
                    { 213, 3, 4, "Central Functionality Planner" },
                    { 212, 9, 8, "Central Intranet Designer" },
                    { 211, 7, 6, "Direct Solutions Technician" },
                    { 210, 10, 3, "Dynamic Metrics Administrator" },
                    { 209, 1, 8, "Dynamic Quality Orchestrator" },
                    { 190, 1, 7, "National Response Liaison" },
                    { 189, 3, 1, "Legacy Accounts Supervisor" },
                    { 188, 0, 9, "Customer Tactics Strategist" },
                    { 187, 10, 8, "Direct Identity Director" },
                    { 167, 8, 8, "Customer Implementation Manager" },
                    { 166, 1, 5, "Future Integration Facilitator" },
                    { 165, 8, 5, "Principal Paradigm Analyst" },
                    { 164, 5, 5, "Forward Creative Representative" },
                    { 163, 6, 1, "Product Infrastructure Coordinator" },
                    { 162, 6, 2, "Internal Communications Liaison" },
                    { 161, 2, 4, "Global Directives Facilitator" },
                    { 160, 3, 2, "Senior Implementation Engineer" },
                    { 159, 9, 6, "Regional Accountability Facilitator" },
                    { 158, 4, 2, "Forward Communications Specialist" },
                    { 157, 4, 2, "Internal Intranet Consultant" },
                    { 156, 8, 1, "Global Paradigm Orchestrator" },
                    { 155, 5, 4, "Forward Marketing Strategist" },
                    { 154, 0, 2, "Global Marketing Consultant" },
                    { 153, 2, 5, "Internal Implementation Associate" },
                    { 168, 8, 5, "Central Response Director" },
                    { 224, 1, 9, "Chief Accounts Developer" },
                    { 169, 6, 1, "Investor Creative Analyst" },
                    { 171, 7, 4, "Human Communications Liaison" },
                    { 186, 5, 8, "Principal Applications Strategist" },
                    { 185, 6, 7, "Dynamic Configuration Consultant" },
                    { 184, 7, 4, "Dynamic Tactics Executive" },
                    { 183, 4, 1, "Customer Data Administrator" },
                    { 182, 10, 2, "Chief Brand Director" },
                    { 181, 2, 9, "Legacy Usability Designer" },
                    { 180, 9, 7, "Direct Web Facilitator" },
                    { 179, 7, 8, "Legacy Optimization Coordinator" },
                    { 178, 5, 9, "Internal Division Engineer" },
                    { 177, 1, 5, "Internal Assurance Coordinator" },
                    { 176, 0, 7, "Internal Response Designer" },
                    { 175, 2, 0, "Regional Intranet Supervisor" },
                    { 174, 4, 6, "Dynamic Tactics Supervisor" },
                    { 173, 0, 1, "Forward Quality Representative" },
                    { 172, 8, 5, "Legacy Communications Executive" },
                    { 170, 3, 3, "Corporate Functionality Facilitator" },
                    { 152, 1, 8, "Internal Markets Designer" },
                    { 225, 10, 5, "District Creative Strategist" },
                    { 227, 7, 5, "Product Usability Director" },
                    { 279, 0, 10, "Lead Research Agent" },
                    { 278, 6, 3, "Principal Paradigm Strategist" },
                    { 277, 9, 10, "Direct Optimization Officer" },
                    { 276, 6, 5, "Product Configuration Planner" },
                    { 275, 7, 6, "Chief Directives Orchestrator" },
                    { 274, 7, 8, "National Research Executive" },
                    { 280, 5, 7, "Investor Branding Facilitator" },
                    { 273, 4, 0, "Direct Factors Orchestrator" },
                    { 271, 0, 8, "Future Solutions Developer" },
                    { 270, 7, 1, "National Creative Planner" },
                    { 269, 6, 8, "Central Solutions Representative" },
                    { 268, 4, 10, "International Solutions Facilitator" },
                    { 267, 3, 8, "District Interactions Facilitator" },
                    { 266, 1, 9, "Senior Tactics Technician" },
                    { 272, 5, 10, "Forward Configuration Technician" },
                    { 281, 8, 9, "Human Brand Assistant" },
                    { 282, 0, 8, "Forward Mobility Orchestrator" },
                    { 283, 0, 2, "Dynamic Response Representative" },
                    { 298, 5, 9, "Lead Accountability Manager" },
                    { 297, 7, 3, "International Usability Specialist" },
                    { 296, 2, 6, "Investor Accounts Coordinator" },
                    { 295, 10, 5, "Corporate Brand Planner" },
                    { 294, 9, 1, "Human Solutions Associate" },
                    { 293, 3, 3, "Human Usability Analyst" },
                    { 292, 1, 3, "Product Infrastructure Supervisor" },
                    { 291, 0, 1, "Central Tactics Specialist" },
                    { 290, 7, 7, "National Implementation Engineer" },
                    { 289, 9, 0, "Investor Intranet Associate" },
                    { 288, 2, 9, "Central Configuration Agent" },
                    { 287, 5, 9, "Product Web Developer" },
                    { 286, 8, 10, "Investor Solutions Engineer" },
                    { 285, 8, 2, "Investor Research Agent" },
                    { 284, 2, 6, "Direct Paradigm Supervisor" },
                    { 265, 5, 9, "Investor Optimization Planner" },
                    { 264, 10, 6, "International Metrics Associate" },
                    { 263, 8, 0, "Investor Group Facilitator" },
                    { 262, 7, 2, "Dynamic Factors Associate" },
                    { 242, 0, 7, "National Communications Architect" },
                    { 241, 3, 3, "International Web Supervisor" },
                    { 240, 2, 7, "Future Accountability Producer" },
                    { 239, 6, 0, "Investor Program Strategist" },
                    { 238, 0, 0, "Chief Mobility Supervisor" },
                    { 237, 5, 5, "Lead Intranet Architect" },
                    { 236, 10, 6, "Direct Tactics Consultant" },
                    { 235, 4, 2, "Investor Operations Architect" },
                    { 234, 3, 0, "Global Identity Agent" },
                    { 233, 1, 10, "Forward Tactics Orchestrator" },
                    { 232, 4, 10, "Future Optimization Associate" },
                    { 231, 9, 3, "Dynamic Program Strategist" },
                    { 230, 3, 0, "Forward Paradigm Assistant" },
                    { 229, 5, 2, "Human Accounts Supervisor" },
                    { 228, 3, 0, "Direct Web Executive" },
                    { 243, 1, 1, "District Markets Administrator" },
                    { 226, 2, 2, "National Directives Coordinator" },
                    { 244, 3, 8, "Lead Configuration Administrator" },
                    { 246, 0, 3, "Future Marketing Developer" },
                    { 261, 10, 4, "Forward Web Facilitator" },
                    { 260, 2, 3, "Forward Infrastructure Strategist" },
                    { 259, 9, 0, "Forward Interactions Assistant" },
                    { 258, 10, 6, "Regional Configuration Consultant" },
                    { 257, 6, 7, "Customer Intranet Technician" },
                    { 256, 5, 6, "National Branding Facilitator" },
                    { 255, 6, 9, "Central Interactions Director" },
                    { 254, 6, 3, "Legacy Operations Agent" },
                    { 253, 9, 5, "Product Functionality Administrator" },
                    { 252, 1, 8, "Senior Applications Coordinator" },
                    { 251, 6, 0, "Dynamic Security Engineer" },
                    { 250, 2, 9, "Direct Program Director" },
                    { 249, 0, 7, "Human Directives Orchestrator" },
                    { 248, 7, 2, "District Division Executive" },
                    { 247, 1, 10, "Senior Solutions Coordinator" },
                    { 245, 8, 5, "National Paradigm Representative" },
                    { 151, 1, 1, "International Applications Producer" },
                    { 150, 3, 5, "Direct Research Engineer" },
                    { 149, 0, 5, "Senior Factors Producer" },
                    { 53, 6, 8, "Product Communications Facilitator" },
                    { 52, 9, 10, "Human Creative Agent" },
                    { 51, 1, 8, "Investor Branding Producer" },
                    { 50, 4, 9, "Direct Creative Specialist" },
                    { 49, 0, 0, "National Mobility Architect" },
                    { 48, 3, 3, "Regional Web Executive" },
                    { 54, 10, 6, "Legacy Division Agent" },
                    { 47, 4, 2, "Principal Division Assistant" },
                    { 45, 1, 6, "Dynamic Accounts Consultant" },
                    { 44, 2, 0, "Investor Research Analyst" },
                    { 43, 10, 6, "Internal Accounts Strategist" },
                    { 42, 1, 4, "Internal Interactions Planner" },
                    { 41, 6, 10, "Human Security Administrator" },
                    { 40, 1, 3, "International Integration Developer" },
                    { 46, 8, 2, "Product Usability Officer" },
                    { 55, 9, 1, "Principal Applications Planner" },
                    { 56, 6, 0, "Chief Security Assistant" },
                    { 57, 10, 5, "Dynamic Metrics Analyst" },
                    { 72, 0, 6, "National Web Planner" },
                    { 71, 4, 1, "Corporate Functionality Facilitator" },
                    { 70, 1, 0, "Dynamic Usability Liaison" },
                    { 69, 4, 4, "Principal Accountability Executive" },
                    { 68, 0, 9, "Future Program Manager" },
                    { 67, 0, 5, "National Functionality Analyst" },
                    { 66, 7, 5, "Human Marketing Architect" },
                    { 65, 4, 7, "Senior Operations Developer" },
                    { 64, 10, 4, "Direct Solutions Representative" },
                    { 63, 10, 9, "National Markets Director" },
                    { 62, 3, 2, "Legacy Accounts Orchestrator" },
                    { 61, 9, 1, "Legacy Brand Officer" },
                    { 60, 9, 9, "Lead Metrics Planner" },
                    { 59, 3, 0, "Principal Creative Analyst" },
                    { 58, 6, 1, "Future Usability Administrator" },
                    { 39, 9, 9, "Human Applications Liaison" },
                    { 38, 4, 1, "National Operations Specialist" },
                    { 37, 6, 1, "Forward Solutions Consultant" },
                    { 36, 5, 6, "Future Tactics Coordinator" },
                    { 16, 1, 7, "Product Identity Orchestrator" },
                    { 15, 8, 3, "Principal Usability Liaison" },
                    { 14, 2, 4, "Chief Functionality Strategist" },
                    { 13, 8, 10, "Direct Data Facilitator" },
                    { 12, 3, 3, "Legacy Mobility Orchestrator" },
                    { 11, 0, 2, "Direct Markets Supervisor" },
                    { 10, 6, 2, "Human Paradigm Supervisor" },
                    { 9, 0, 8, "Dynamic Directives Engineer" },
                    { 8, 7, 9, "Future Integration Designer" },
                    { 7, 5, 0, "Internal Integration Coordinator" },
                    { 6, 3, 0, "Dynamic Identity Supervisor" },
                    { 5, 0, 1, "Customer Directives Consultant" },
                    { 4, 6, 7, "Principal Usability Specialist" },
                    { 3, 8, 7, "Corporate Infrastructure Planner" },
                    { 2, 7, 6, "Dynamic Accountability Analyst" },
                    { 17, 10, 8, "Lead Accounts Specialist" },
                    { 73, 8, 8, "International Group Consultant" },
                    { 18, 7, 8, "Direct Response Consultant" },
                    { 20, 4, 1, "Global Directives Producer" },
                    { 35, 8, 4, "Regional Brand Producer" },
                    { 34, 0, 2, "Investor Operations Agent" },
                    { 33, 3, 0, "Lead Factors Analyst" },
                    { 32, 4, 2, "Dynamic Directives Planner" },
                    { 31, 1, 5, "Forward Applications Liaison" },
                    { 30, 1, 2, "Human Functionality Technician" },
                    { 29, 10, 4, "Direct Marketing Administrator" },
                    { 28, 0, 9, "Chief Paradigm Supervisor" },
                    { 27, 6, 6, "Direct Accountability Consultant" },
                    { 26, 7, 8, "Product Accounts Associate" },
                    { 25, 4, 2, "Direct Division Planner" },
                    { 24, 10, 10, "Product Tactics Planner" },
                    { 23, 9, 3, "Dynamic Data Producer" },
                    { 22, 5, 1, "Internal Accounts Consultant" },
                    { 21, 10, 6, "International Brand Officer" },
                    { 19, 10, 8, "District Integration Representative" },
                    { 74, 6, 10, "Principal Brand Strategist" },
                    { 75, 8, 4, "District Intranet Orchestrator" },
                    { 76, 0, 7, "Product Tactics Supervisor" },
                    { 129, 3, 2, "Lead Functionality Liaison" },
                    { 128, 6, 9, "District Configuration Engineer" },
                    { 127, 0, 10, "Investor Solutions Agent" },
                    { 126, 10, 5, "Internal Intranet Producer" },
                    { 125, 9, 3, "Global Usability Supervisor" },
                    { 124, 4, 9, "Senior Quality Associate" },
                    { 123, 10, 3, "Internal Factors Architect" },
                    { 122, 6, 10, "Legacy Usability Assistant" },
                    { 121, 7, 3, "Dynamic Quality Planner" },
                    { 120, 5, 0, "Chief Factors Strategist" },
                    { 119, 7, 6, "Dynamic Security Coordinator" },
                    { 118, 10, 1, "Human Identity Specialist" },
                    { 117, 6, 8, "Product Directives Consultant" },
                    { 116, 1, 3, "Global Brand Planner" },
                    { 115, 7, 8, "Dynamic Metrics Architect" },
                    { 130, 10, 3, "Principal Markets Specialist" },
                    { 114, 8, 9, "Central Infrastructure Specialist" },
                    { 131, 4, 9, "Dynamic Security Facilitator" },
                    { 133, 10, 9, "Dynamic Solutions Architect" },
                    { 148, 8, 9, "Senior Configuration Engineer" },
                    { 147, 7, 3, "Regional Infrastructure Producer" },
                    { 146, 9, 6, "Central Identity Coordinator" },
                    { 145, 10, 5, "Internal Identity Orchestrator" },
                    { 144, 4, 1, "National Accountability Orchestrator" },
                    { 143, 0, 0, "Investor Group Supervisor" },
                    { 142, 3, 7, "Internal Assurance Associate" },
                    { 141, 5, 9, "Dynamic Implementation Agent" },
                    { 140, 9, 5, "National Research Producer" },
                    { 139, 8, 7, "Regional Implementation Manager" },
                    { 138, 10, 5, "District Metrics Designer" },
                    { 137, 4, 4, "Product Factors Facilitator" },
                    { 136, 5, 3, "Product Assurance Analyst" },
                    { 135, 9, 4, "Dynamic Identity Manager" },
                    { 134, 6, 5, "Lead Applications Administrator" },
                    { 132, 8, 9, "Global Operations Administrator" },
                    { 299, 2, 10, "Internal Metrics Director" },
                    { 113, 10, 9, "Principal Mobility Agent" },
                    { 111, 4, 0, "Central Accountability Officer" },
                    { 91, 2, 0, "Forward Implementation Representative" },
                    { 90, 2, 0, "International Program Coordinator" },
                    { 89, 6, 6, "Product Division Orchestrator" },
                    { 88, 10, 9, "Forward Data Coordinator" },
                    { 87, 4, 9, "Regional Program Facilitator" },
                    { 86, 8, 10, "Forward Data Strategist" },
                    { 85, 4, 5, "Principal Branding Executive" },
                    { 84, 5, 6, "Chief Assurance Supervisor" },
                    { 83, 2, 5, "National Division Officer" },
                    { 82, 5, 5, "Investor Directives Consultant" },
                    { 81, 1, 10, "Global Integration Developer" },
                    { 80, 3, 2, "Global Security Consultant" },
                    { 79, 6, 1, "Senior Paradigm Administrator" },
                    { 78, 6, 0, "Chief Accountability Consultant" },
                    { 77, 0, 7, "Lead Creative Director" },
                    { 92, 4, 4, "Regional Research Engineer" },
                    { 112, 1, 6, "Legacy Directives Associate" },
                    { 93, 8, 6, "Dynamic Response Technician" },
                    { 95, 9, 3, "Lead Research Technician" },
                    { 110, 8, 6, "Future Implementation Officer" },
                    { 109, 3, 1, "Forward Quality Associate" },
                    { 108, 2, 0, "Customer Interactions Administrator" },
                    { 107, 1, 1, "Chief Infrastructure Assistant" },
                    { 106, 6, 9, "Principal Configuration Analyst" },
                    { 105, 3, 1, "Internal Assurance Officer" },
                    { 104, 8, 0, "International Infrastructure Agent" },
                    { 103, 7, 1, "Customer Response Architect" },
                    { 102, 1, 6, "International Assurance Supervisor" },
                    { 101, 6, 2, "Dynamic Markets Manager" },
                    { 100, 5, 1, "Central Intranet Orchestrator" },
                    { 99, 8, 9, "Global Accountability Director" },
                    { 98, 3, 4, "Product Branding Designer" },
                    { 97, 0, 0, "International Metrics Facilitator" },
                    { 96, 0, 3, "Dynamic Communications Supervisor" },
                    { 94, 2, 8, "Chief Branding Manager" },
                    { 300, 2, 2, "Dynamic Identity Liaison" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Superheroes",
                schema: "Shb");
        }
    }
}
