// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shb.Infrastructure.Persistence.Database;

namespace Shb.Infrastructure.Migrations
{
    [DbContext(typeof(ShbContext))]
    [Migration("20201031220700_ShbInit")]
    partial class ShbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Shb")
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shb.Domain.Models.Superhero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack")
                        .HasColumnName("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnName("Defence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 0,
                            Defence = 0,
                            Name = "Customer Marketing Officer"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 7,
                            Defence = 6,
                            Name = "Dynamic Accountability Analyst"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 8,
                            Defence = 7,
                            Name = "Corporate Infrastructure Planner"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 6,
                            Defence = 7,
                            Name = "Principal Usability Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 0,
                            Defence = 1,
                            Name = "Customer Directives Consultant"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 3,
                            Defence = 0,
                            Name = "Dynamic Identity Supervisor"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 5,
                            Defence = 0,
                            Name = "Internal Integration Coordinator"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 7,
                            Defence = 9,
                            Name = "Future Integration Designer"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 0,
                            Defence = 8,
                            Name = "Dynamic Directives Engineer"
                        },
                        new
                        {
                            Id = 10,
                            Attack = 6,
                            Defence = 2,
                            Name = "Human Paradigm Supervisor"
                        },
                        new
                        {
                            Id = 11,
                            Attack = 0,
                            Defence = 2,
                            Name = "Direct Markets Supervisor"
                        },
                        new
                        {
                            Id = 12,
                            Attack = 3,
                            Defence = 3,
                            Name = "Legacy Mobility Orchestrator"
                        },
                        new
                        {
                            Id = 13,
                            Attack = 8,
                            Defence = 10,
                            Name = "Direct Data Facilitator"
                        },
                        new
                        {
                            Id = 14,
                            Attack = 2,
                            Defence = 4,
                            Name = "Chief Functionality Strategist"
                        },
                        new
                        {
                            Id = 15,
                            Attack = 8,
                            Defence = 3,
                            Name = "Principal Usability Liaison"
                        },
                        new
                        {
                            Id = 16,
                            Attack = 1,
                            Defence = 7,
                            Name = "Product Identity Orchestrator"
                        },
                        new
                        {
                            Id = 17,
                            Attack = 10,
                            Defence = 8,
                            Name = "Lead Accounts Specialist"
                        },
                        new
                        {
                            Id = 18,
                            Attack = 7,
                            Defence = 8,
                            Name = "Direct Response Consultant"
                        },
                        new
                        {
                            Id = 19,
                            Attack = 10,
                            Defence = 8,
                            Name = "District Integration Representative"
                        },
                        new
                        {
                            Id = 20,
                            Attack = 4,
                            Defence = 1,
                            Name = "Global Directives Producer"
                        },
                        new
                        {
                            Id = 21,
                            Attack = 10,
                            Defence = 6,
                            Name = "International Brand Officer"
                        },
                        new
                        {
                            Id = 22,
                            Attack = 5,
                            Defence = 1,
                            Name = "Internal Accounts Consultant"
                        },
                        new
                        {
                            Id = 23,
                            Attack = 9,
                            Defence = 3,
                            Name = "Dynamic Data Producer"
                        },
                        new
                        {
                            Id = 24,
                            Attack = 10,
                            Defence = 10,
                            Name = "Product Tactics Planner"
                        },
                        new
                        {
                            Id = 25,
                            Attack = 4,
                            Defence = 2,
                            Name = "Direct Division Planner"
                        },
                        new
                        {
                            Id = 26,
                            Attack = 7,
                            Defence = 8,
                            Name = "Product Accounts Associate"
                        },
                        new
                        {
                            Id = 27,
                            Attack = 6,
                            Defence = 6,
                            Name = "Direct Accountability Consultant"
                        },
                        new
                        {
                            Id = 28,
                            Attack = 0,
                            Defence = 9,
                            Name = "Chief Paradigm Supervisor"
                        },
                        new
                        {
                            Id = 29,
                            Attack = 10,
                            Defence = 4,
                            Name = "Direct Marketing Administrator"
                        },
                        new
                        {
                            Id = 30,
                            Attack = 1,
                            Defence = 2,
                            Name = "Human Functionality Technician"
                        },
                        new
                        {
                            Id = 31,
                            Attack = 1,
                            Defence = 5,
                            Name = "Forward Applications Liaison"
                        },
                        new
                        {
                            Id = 32,
                            Attack = 4,
                            Defence = 2,
                            Name = "Dynamic Directives Planner"
                        },
                        new
                        {
                            Id = 33,
                            Attack = 3,
                            Defence = 0,
                            Name = "Lead Factors Analyst"
                        },
                        new
                        {
                            Id = 34,
                            Attack = 0,
                            Defence = 2,
                            Name = "Investor Operations Agent"
                        },
                        new
                        {
                            Id = 35,
                            Attack = 8,
                            Defence = 4,
                            Name = "Regional Brand Producer"
                        },
                        new
                        {
                            Id = 36,
                            Attack = 5,
                            Defence = 6,
                            Name = "Future Tactics Coordinator"
                        },
                        new
                        {
                            Id = 37,
                            Attack = 6,
                            Defence = 1,
                            Name = "Forward Solutions Consultant"
                        },
                        new
                        {
                            Id = 38,
                            Attack = 4,
                            Defence = 1,
                            Name = "National Operations Specialist"
                        },
                        new
                        {
                            Id = 39,
                            Attack = 9,
                            Defence = 9,
                            Name = "Human Applications Liaison"
                        },
                        new
                        {
                            Id = 40,
                            Attack = 1,
                            Defence = 3,
                            Name = "International Integration Developer"
                        },
                        new
                        {
                            Id = 41,
                            Attack = 6,
                            Defence = 10,
                            Name = "Human Security Administrator"
                        },
                        new
                        {
                            Id = 42,
                            Attack = 1,
                            Defence = 4,
                            Name = "Internal Interactions Planner"
                        },
                        new
                        {
                            Id = 43,
                            Attack = 10,
                            Defence = 6,
                            Name = "Internal Accounts Strategist"
                        },
                        new
                        {
                            Id = 44,
                            Attack = 2,
                            Defence = 0,
                            Name = "Investor Research Analyst"
                        },
                        new
                        {
                            Id = 45,
                            Attack = 1,
                            Defence = 6,
                            Name = "Dynamic Accounts Consultant"
                        },
                        new
                        {
                            Id = 46,
                            Attack = 8,
                            Defence = 2,
                            Name = "Product Usability Officer"
                        },
                        new
                        {
                            Id = 47,
                            Attack = 4,
                            Defence = 2,
                            Name = "Principal Division Assistant"
                        },
                        new
                        {
                            Id = 48,
                            Attack = 3,
                            Defence = 3,
                            Name = "Regional Web Executive"
                        },
                        new
                        {
                            Id = 49,
                            Attack = 0,
                            Defence = 0,
                            Name = "National Mobility Architect"
                        },
                        new
                        {
                            Id = 50,
                            Attack = 4,
                            Defence = 9,
                            Name = "Direct Creative Specialist"
                        },
                        new
                        {
                            Id = 51,
                            Attack = 1,
                            Defence = 8,
                            Name = "Investor Branding Producer"
                        },
                        new
                        {
                            Id = 52,
                            Attack = 9,
                            Defence = 10,
                            Name = "Human Creative Agent"
                        },
                        new
                        {
                            Id = 53,
                            Attack = 6,
                            Defence = 8,
                            Name = "Product Communications Facilitator"
                        },
                        new
                        {
                            Id = 54,
                            Attack = 10,
                            Defence = 6,
                            Name = "Legacy Division Agent"
                        },
                        new
                        {
                            Id = 55,
                            Attack = 9,
                            Defence = 1,
                            Name = "Principal Applications Planner"
                        },
                        new
                        {
                            Id = 56,
                            Attack = 6,
                            Defence = 0,
                            Name = "Chief Security Assistant"
                        },
                        new
                        {
                            Id = 57,
                            Attack = 10,
                            Defence = 5,
                            Name = "Dynamic Metrics Analyst"
                        },
                        new
                        {
                            Id = 58,
                            Attack = 6,
                            Defence = 1,
                            Name = "Future Usability Administrator"
                        },
                        new
                        {
                            Id = 59,
                            Attack = 3,
                            Defence = 0,
                            Name = "Principal Creative Analyst"
                        },
                        new
                        {
                            Id = 60,
                            Attack = 9,
                            Defence = 9,
                            Name = "Lead Metrics Planner"
                        },
                        new
                        {
                            Id = 61,
                            Attack = 9,
                            Defence = 1,
                            Name = "Legacy Brand Officer"
                        },
                        new
                        {
                            Id = 62,
                            Attack = 3,
                            Defence = 2,
                            Name = "Legacy Accounts Orchestrator"
                        },
                        new
                        {
                            Id = 63,
                            Attack = 10,
                            Defence = 9,
                            Name = "National Markets Director"
                        },
                        new
                        {
                            Id = 64,
                            Attack = 10,
                            Defence = 4,
                            Name = "Direct Solutions Representative"
                        },
                        new
                        {
                            Id = 65,
                            Attack = 4,
                            Defence = 7,
                            Name = "Senior Operations Developer"
                        },
                        new
                        {
                            Id = 66,
                            Attack = 7,
                            Defence = 5,
                            Name = "Human Marketing Architect"
                        },
                        new
                        {
                            Id = 67,
                            Attack = 0,
                            Defence = 5,
                            Name = "National Functionality Analyst"
                        },
                        new
                        {
                            Id = 68,
                            Attack = 0,
                            Defence = 9,
                            Name = "Future Program Manager"
                        },
                        new
                        {
                            Id = 69,
                            Attack = 4,
                            Defence = 4,
                            Name = "Principal Accountability Executive"
                        },
                        new
                        {
                            Id = 70,
                            Attack = 1,
                            Defence = 0,
                            Name = "Dynamic Usability Liaison"
                        },
                        new
                        {
                            Id = 71,
                            Attack = 4,
                            Defence = 1,
                            Name = "Corporate Functionality Facilitator"
                        },
                        new
                        {
                            Id = 72,
                            Attack = 0,
                            Defence = 6,
                            Name = "National Web Planner"
                        },
                        new
                        {
                            Id = 73,
                            Attack = 8,
                            Defence = 8,
                            Name = "International Group Consultant"
                        },
                        new
                        {
                            Id = 74,
                            Attack = 6,
                            Defence = 10,
                            Name = "Principal Brand Strategist"
                        },
                        new
                        {
                            Id = 75,
                            Attack = 8,
                            Defence = 4,
                            Name = "District Intranet Orchestrator"
                        },
                        new
                        {
                            Id = 76,
                            Attack = 0,
                            Defence = 7,
                            Name = "Product Tactics Supervisor"
                        },
                        new
                        {
                            Id = 77,
                            Attack = 0,
                            Defence = 7,
                            Name = "Lead Creative Director"
                        },
                        new
                        {
                            Id = 78,
                            Attack = 6,
                            Defence = 0,
                            Name = "Chief Accountability Consultant"
                        },
                        new
                        {
                            Id = 79,
                            Attack = 6,
                            Defence = 1,
                            Name = "Senior Paradigm Administrator"
                        },
                        new
                        {
                            Id = 80,
                            Attack = 3,
                            Defence = 2,
                            Name = "Global Security Consultant"
                        },
                        new
                        {
                            Id = 81,
                            Attack = 1,
                            Defence = 10,
                            Name = "Global Integration Developer"
                        },
                        new
                        {
                            Id = 82,
                            Attack = 5,
                            Defence = 5,
                            Name = "Investor Directives Consultant"
                        },
                        new
                        {
                            Id = 83,
                            Attack = 2,
                            Defence = 5,
                            Name = "National Division Officer"
                        },
                        new
                        {
                            Id = 84,
                            Attack = 5,
                            Defence = 6,
                            Name = "Chief Assurance Supervisor"
                        },
                        new
                        {
                            Id = 85,
                            Attack = 4,
                            Defence = 5,
                            Name = "Principal Branding Executive"
                        },
                        new
                        {
                            Id = 86,
                            Attack = 8,
                            Defence = 10,
                            Name = "Forward Data Strategist"
                        },
                        new
                        {
                            Id = 87,
                            Attack = 4,
                            Defence = 9,
                            Name = "Regional Program Facilitator"
                        },
                        new
                        {
                            Id = 88,
                            Attack = 10,
                            Defence = 9,
                            Name = "Forward Data Coordinator"
                        },
                        new
                        {
                            Id = 89,
                            Attack = 6,
                            Defence = 6,
                            Name = "Product Division Orchestrator"
                        },
                        new
                        {
                            Id = 90,
                            Attack = 2,
                            Defence = 0,
                            Name = "International Program Coordinator"
                        },
                        new
                        {
                            Id = 91,
                            Attack = 2,
                            Defence = 0,
                            Name = "Forward Implementation Representative"
                        },
                        new
                        {
                            Id = 92,
                            Attack = 4,
                            Defence = 4,
                            Name = "Regional Research Engineer"
                        },
                        new
                        {
                            Id = 93,
                            Attack = 8,
                            Defence = 6,
                            Name = "Dynamic Response Technician"
                        },
                        new
                        {
                            Id = 94,
                            Attack = 2,
                            Defence = 8,
                            Name = "Chief Branding Manager"
                        },
                        new
                        {
                            Id = 95,
                            Attack = 9,
                            Defence = 3,
                            Name = "Lead Research Technician"
                        },
                        new
                        {
                            Id = 96,
                            Attack = 0,
                            Defence = 3,
                            Name = "Dynamic Communications Supervisor"
                        },
                        new
                        {
                            Id = 97,
                            Attack = 0,
                            Defence = 0,
                            Name = "International Metrics Facilitator"
                        },
                        new
                        {
                            Id = 98,
                            Attack = 3,
                            Defence = 4,
                            Name = "Product Branding Designer"
                        },
                        new
                        {
                            Id = 99,
                            Attack = 8,
                            Defence = 9,
                            Name = "Global Accountability Director"
                        },
                        new
                        {
                            Id = 100,
                            Attack = 5,
                            Defence = 1,
                            Name = "Central Intranet Orchestrator"
                        },
                        new
                        {
                            Id = 101,
                            Attack = 6,
                            Defence = 2,
                            Name = "Dynamic Markets Manager"
                        },
                        new
                        {
                            Id = 102,
                            Attack = 1,
                            Defence = 6,
                            Name = "International Assurance Supervisor"
                        },
                        new
                        {
                            Id = 103,
                            Attack = 7,
                            Defence = 1,
                            Name = "Customer Response Architect"
                        },
                        new
                        {
                            Id = 104,
                            Attack = 8,
                            Defence = 0,
                            Name = "International Infrastructure Agent"
                        },
                        new
                        {
                            Id = 105,
                            Attack = 3,
                            Defence = 1,
                            Name = "Internal Assurance Officer"
                        },
                        new
                        {
                            Id = 106,
                            Attack = 6,
                            Defence = 9,
                            Name = "Principal Configuration Analyst"
                        },
                        new
                        {
                            Id = 107,
                            Attack = 1,
                            Defence = 1,
                            Name = "Chief Infrastructure Assistant"
                        },
                        new
                        {
                            Id = 108,
                            Attack = 2,
                            Defence = 0,
                            Name = "Customer Interactions Administrator"
                        },
                        new
                        {
                            Id = 109,
                            Attack = 3,
                            Defence = 1,
                            Name = "Forward Quality Associate"
                        },
                        new
                        {
                            Id = 110,
                            Attack = 8,
                            Defence = 6,
                            Name = "Future Implementation Officer"
                        },
                        new
                        {
                            Id = 111,
                            Attack = 4,
                            Defence = 0,
                            Name = "Central Accountability Officer"
                        },
                        new
                        {
                            Id = 112,
                            Attack = 1,
                            Defence = 6,
                            Name = "Legacy Directives Associate"
                        },
                        new
                        {
                            Id = 113,
                            Attack = 10,
                            Defence = 9,
                            Name = "Principal Mobility Agent"
                        },
                        new
                        {
                            Id = 114,
                            Attack = 8,
                            Defence = 9,
                            Name = "Central Infrastructure Specialist"
                        },
                        new
                        {
                            Id = 115,
                            Attack = 7,
                            Defence = 8,
                            Name = "Dynamic Metrics Architect"
                        },
                        new
                        {
                            Id = 116,
                            Attack = 1,
                            Defence = 3,
                            Name = "Global Brand Planner"
                        },
                        new
                        {
                            Id = 117,
                            Attack = 6,
                            Defence = 8,
                            Name = "Product Directives Consultant"
                        },
                        new
                        {
                            Id = 118,
                            Attack = 10,
                            Defence = 1,
                            Name = "Human Identity Specialist"
                        },
                        new
                        {
                            Id = 119,
                            Attack = 7,
                            Defence = 6,
                            Name = "Dynamic Security Coordinator"
                        },
                        new
                        {
                            Id = 120,
                            Attack = 5,
                            Defence = 0,
                            Name = "Chief Factors Strategist"
                        },
                        new
                        {
                            Id = 121,
                            Attack = 7,
                            Defence = 3,
                            Name = "Dynamic Quality Planner"
                        },
                        new
                        {
                            Id = 122,
                            Attack = 6,
                            Defence = 10,
                            Name = "Legacy Usability Assistant"
                        },
                        new
                        {
                            Id = 123,
                            Attack = 10,
                            Defence = 3,
                            Name = "Internal Factors Architect"
                        },
                        new
                        {
                            Id = 124,
                            Attack = 4,
                            Defence = 9,
                            Name = "Senior Quality Associate"
                        },
                        new
                        {
                            Id = 125,
                            Attack = 9,
                            Defence = 3,
                            Name = "Global Usability Supervisor"
                        },
                        new
                        {
                            Id = 126,
                            Attack = 10,
                            Defence = 5,
                            Name = "Internal Intranet Producer"
                        },
                        new
                        {
                            Id = 127,
                            Attack = 0,
                            Defence = 10,
                            Name = "Investor Solutions Agent"
                        },
                        new
                        {
                            Id = 128,
                            Attack = 6,
                            Defence = 9,
                            Name = "District Configuration Engineer"
                        },
                        new
                        {
                            Id = 129,
                            Attack = 3,
                            Defence = 2,
                            Name = "Lead Functionality Liaison"
                        },
                        new
                        {
                            Id = 130,
                            Attack = 10,
                            Defence = 3,
                            Name = "Principal Markets Specialist"
                        },
                        new
                        {
                            Id = 131,
                            Attack = 4,
                            Defence = 9,
                            Name = "Dynamic Security Facilitator"
                        },
                        new
                        {
                            Id = 132,
                            Attack = 8,
                            Defence = 9,
                            Name = "Global Operations Administrator"
                        },
                        new
                        {
                            Id = 133,
                            Attack = 10,
                            Defence = 9,
                            Name = "Dynamic Solutions Architect"
                        },
                        new
                        {
                            Id = 134,
                            Attack = 6,
                            Defence = 5,
                            Name = "Lead Applications Administrator"
                        },
                        new
                        {
                            Id = 135,
                            Attack = 9,
                            Defence = 4,
                            Name = "Dynamic Identity Manager"
                        },
                        new
                        {
                            Id = 136,
                            Attack = 5,
                            Defence = 3,
                            Name = "Product Assurance Analyst"
                        },
                        new
                        {
                            Id = 137,
                            Attack = 4,
                            Defence = 4,
                            Name = "Product Factors Facilitator"
                        },
                        new
                        {
                            Id = 138,
                            Attack = 10,
                            Defence = 5,
                            Name = "District Metrics Designer"
                        },
                        new
                        {
                            Id = 139,
                            Attack = 8,
                            Defence = 7,
                            Name = "Regional Implementation Manager"
                        },
                        new
                        {
                            Id = 140,
                            Attack = 9,
                            Defence = 5,
                            Name = "National Research Producer"
                        },
                        new
                        {
                            Id = 141,
                            Attack = 5,
                            Defence = 9,
                            Name = "Dynamic Implementation Agent"
                        },
                        new
                        {
                            Id = 142,
                            Attack = 3,
                            Defence = 7,
                            Name = "Internal Assurance Associate"
                        },
                        new
                        {
                            Id = 143,
                            Attack = 0,
                            Defence = 0,
                            Name = "Investor Group Supervisor"
                        },
                        new
                        {
                            Id = 144,
                            Attack = 4,
                            Defence = 1,
                            Name = "National Accountability Orchestrator"
                        },
                        new
                        {
                            Id = 145,
                            Attack = 10,
                            Defence = 5,
                            Name = "Internal Identity Orchestrator"
                        },
                        new
                        {
                            Id = 146,
                            Attack = 9,
                            Defence = 6,
                            Name = "Central Identity Coordinator"
                        },
                        new
                        {
                            Id = 147,
                            Attack = 7,
                            Defence = 3,
                            Name = "Regional Infrastructure Producer"
                        },
                        new
                        {
                            Id = 148,
                            Attack = 8,
                            Defence = 9,
                            Name = "Senior Configuration Engineer"
                        },
                        new
                        {
                            Id = 149,
                            Attack = 0,
                            Defence = 5,
                            Name = "Senior Factors Producer"
                        },
                        new
                        {
                            Id = 150,
                            Attack = 3,
                            Defence = 5,
                            Name = "Direct Research Engineer"
                        },
                        new
                        {
                            Id = 151,
                            Attack = 1,
                            Defence = 1,
                            Name = "International Applications Producer"
                        },
                        new
                        {
                            Id = 152,
                            Attack = 1,
                            Defence = 8,
                            Name = "Internal Markets Designer"
                        },
                        new
                        {
                            Id = 153,
                            Attack = 2,
                            Defence = 5,
                            Name = "Internal Implementation Associate"
                        },
                        new
                        {
                            Id = 154,
                            Attack = 0,
                            Defence = 2,
                            Name = "Global Marketing Consultant"
                        },
                        new
                        {
                            Id = 155,
                            Attack = 5,
                            Defence = 4,
                            Name = "Forward Marketing Strategist"
                        },
                        new
                        {
                            Id = 156,
                            Attack = 8,
                            Defence = 1,
                            Name = "Global Paradigm Orchestrator"
                        },
                        new
                        {
                            Id = 157,
                            Attack = 4,
                            Defence = 2,
                            Name = "Internal Intranet Consultant"
                        },
                        new
                        {
                            Id = 158,
                            Attack = 4,
                            Defence = 2,
                            Name = "Forward Communications Specialist"
                        },
                        new
                        {
                            Id = 159,
                            Attack = 9,
                            Defence = 6,
                            Name = "Regional Accountability Facilitator"
                        },
                        new
                        {
                            Id = 160,
                            Attack = 3,
                            Defence = 2,
                            Name = "Senior Implementation Engineer"
                        },
                        new
                        {
                            Id = 161,
                            Attack = 2,
                            Defence = 4,
                            Name = "Global Directives Facilitator"
                        },
                        new
                        {
                            Id = 162,
                            Attack = 6,
                            Defence = 2,
                            Name = "Internal Communications Liaison"
                        },
                        new
                        {
                            Id = 163,
                            Attack = 6,
                            Defence = 1,
                            Name = "Product Infrastructure Coordinator"
                        },
                        new
                        {
                            Id = 164,
                            Attack = 5,
                            Defence = 5,
                            Name = "Forward Creative Representative"
                        },
                        new
                        {
                            Id = 165,
                            Attack = 8,
                            Defence = 5,
                            Name = "Principal Paradigm Analyst"
                        },
                        new
                        {
                            Id = 166,
                            Attack = 1,
                            Defence = 5,
                            Name = "Future Integration Facilitator"
                        },
                        new
                        {
                            Id = 167,
                            Attack = 8,
                            Defence = 8,
                            Name = "Customer Implementation Manager"
                        },
                        new
                        {
                            Id = 168,
                            Attack = 8,
                            Defence = 5,
                            Name = "Central Response Director"
                        },
                        new
                        {
                            Id = 169,
                            Attack = 6,
                            Defence = 1,
                            Name = "Investor Creative Analyst"
                        },
                        new
                        {
                            Id = 170,
                            Attack = 3,
                            Defence = 3,
                            Name = "Corporate Functionality Facilitator"
                        },
                        new
                        {
                            Id = 171,
                            Attack = 7,
                            Defence = 4,
                            Name = "Human Communications Liaison"
                        },
                        new
                        {
                            Id = 172,
                            Attack = 8,
                            Defence = 5,
                            Name = "Legacy Communications Executive"
                        },
                        new
                        {
                            Id = 173,
                            Attack = 0,
                            Defence = 1,
                            Name = "Forward Quality Representative"
                        },
                        new
                        {
                            Id = 174,
                            Attack = 4,
                            Defence = 6,
                            Name = "Dynamic Tactics Supervisor"
                        },
                        new
                        {
                            Id = 175,
                            Attack = 2,
                            Defence = 0,
                            Name = "Regional Intranet Supervisor"
                        },
                        new
                        {
                            Id = 176,
                            Attack = 0,
                            Defence = 7,
                            Name = "Internal Response Designer"
                        },
                        new
                        {
                            Id = 177,
                            Attack = 1,
                            Defence = 5,
                            Name = "Internal Assurance Coordinator"
                        },
                        new
                        {
                            Id = 178,
                            Attack = 5,
                            Defence = 9,
                            Name = "Internal Division Engineer"
                        },
                        new
                        {
                            Id = 179,
                            Attack = 7,
                            Defence = 8,
                            Name = "Legacy Optimization Coordinator"
                        },
                        new
                        {
                            Id = 180,
                            Attack = 9,
                            Defence = 7,
                            Name = "Direct Web Facilitator"
                        },
                        new
                        {
                            Id = 181,
                            Attack = 2,
                            Defence = 9,
                            Name = "Legacy Usability Designer"
                        },
                        new
                        {
                            Id = 182,
                            Attack = 10,
                            Defence = 2,
                            Name = "Chief Brand Director"
                        },
                        new
                        {
                            Id = 183,
                            Attack = 4,
                            Defence = 1,
                            Name = "Customer Data Administrator"
                        },
                        new
                        {
                            Id = 184,
                            Attack = 7,
                            Defence = 4,
                            Name = "Dynamic Tactics Executive"
                        },
                        new
                        {
                            Id = 185,
                            Attack = 6,
                            Defence = 7,
                            Name = "Dynamic Configuration Consultant"
                        },
                        new
                        {
                            Id = 186,
                            Attack = 5,
                            Defence = 8,
                            Name = "Principal Applications Strategist"
                        },
                        new
                        {
                            Id = 187,
                            Attack = 10,
                            Defence = 8,
                            Name = "Direct Identity Director"
                        },
                        new
                        {
                            Id = 188,
                            Attack = 0,
                            Defence = 9,
                            Name = "Customer Tactics Strategist"
                        },
                        new
                        {
                            Id = 189,
                            Attack = 3,
                            Defence = 1,
                            Name = "Legacy Accounts Supervisor"
                        },
                        new
                        {
                            Id = 190,
                            Attack = 1,
                            Defence = 7,
                            Name = "National Response Liaison"
                        },
                        new
                        {
                            Id = 191,
                            Attack = 0,
                            Defence = 9,
                            Name = "Customer Program Representative"
                        },
                        new
                        {
                            Id = 192,
                            Attack = 10,
                            Defence = 1,
                            Name = "District Usability Facilitator"
                        },
                        new
                        {
                            Id = 193,
                            Attack = 3,
                            Defence = 5,
                            Name = "International Functionality Officer"
                        },
                        new
                        {
                            Id = 194,
                            Attack = 1,
                            Defence = 7,
                            Name = "Future Intranet Associate"
                        },
                        new
                        {
                            Id = 195,
                            Attack = 8,
                            Defence = 0,
                            Name = "Forward Interactions Assistant"
                        },
                        new
                        {
                            Id = 196,
                            Attack = 1,
                            Defence = 0,
                            Name = "Global Communications Producer"
                        },
                        new
                        {
                            Id = 197,
                            Attack = 0,
                            Defence = 2,
                            Name = "Dynamic Solutions Officer"
                        },
                        new
                        {
                            Id = 198,
                            Attack = 3,
                            Defence = 4,
                            Name = "Lead Tactics Coordinator"
                        },
                        new
                        {
                            Id = 199,
                            Attack = 0,
                            Defence = 10,
                            Name = "Human Accounts Engineer"
                        },
                        new
                        {
                            Id = 200,
                            Attack = 6,
                            Defence = 0,
                            Name = "Product Branding Officer"
                        },
                        new
                        {
                            Id = 201,
                            Attack = 2,
                            Defence = 6,
                            Name = "Human Functionality Engineer"
                        },
                        new
                        {
                            Id = 202,
                            Attack = 10,
                            Defence = 8,
                            Name = "Global Tactics Administrator"
                        },
                        new
                        {
                            Id = 203,
                            Attack = 1,
                            Defence = 6,
                            Name = "Lead Functionality Director"
                        },
                        new
                        {
                            Id = 204,
                            Attack = 7,
                            Defence = 7,
                            Name = "Customer Communications Consultant"
                        },
                        new
                        {
                            Id = 205,
                            Attack = 1,
                            Defence = 4,
                            Name = "Dynamic Assurance Planner"
                        },
                        new
                        {
                            Id = 206,
                            Attack = 10,
                            Defence = 7,
                            Name = "Senior Paradigm Analyst"
                        },
                        new
                        {
                            Id = 207,
                            Attack = 6,
                            Defence = 6,
                            Name = "National Communications Executive"
                        },
                        new
                        {
                            Id = 208,
                            Attack = 2,
                            Defence = 1,
                            Name = "Forward Accountability Manager"
                        },
                        new
                        {
                            Id = 209,
                            Attack = 1,
                            Defence = 8,
                            Name = "Dynamic Quality Orchestrator"
                        },
                        new
                        {
                            Id = 210,
                            Attack = 10,
                            Defence = 3,
                            Name = "Dynamic Metrics Administrator"
                        },
                        new
                        {
                            Id = 211,
                            Attack = 7,
                            Defence = 6,
                            Name = "Direct Solutions Technician"
                        },
                        new
                        {
                            Id = 212,
                            Attack = 9,
                            Defence = 8,
                            Name = "Central Intranet Designer"
                        },
                        new
                        {
                            Id = 213,
                            Attack = 3,
                            Defence = 4,
                            Name = "Central Functionality Planner"
                        },
                        new
                        {
                            Id = 214,
                            Attack = 9,
                            Defence = 10,
                            Name = "District Brand Manager"
                        },
                        new
                        {
                            Id = 215,
                            Attack = 3,
                            Defence = 4,
                            Name = "Global Solutions Strategist"
                        },
                        new
                        {
                            Id = 216,
                            Attack = 4,
                            Defence = 3,
                            Name = "Global Assurance Assistant"
                        },
                        new
                        {
                            Id = 217,
                            Attack = 8,
                            Defence = 9,
                            Name = "Corporate Brand Planner"
                        },
                        new
                        {
                            Id = 218,
                            Attack = 7,
                            Defence = 9,
                            Name = "Corporate Operations Representative"
                        },
                        new
                        {
                            Id = 219,
                            Attack = 3,
                            Defence = 5,
                            Name = "Regional Brand Analyst"
                        },
                        new
                        {
                            Id = 220,
                            Attack = 3,
                            Defence = 5,
                            Name = "Chief Marketing Technician"
                        },
                        new
                        {
                            Id = 221,
                            Attack = 6,
                            Defence = 10,
                            Name = "Lead Implementation Liaison"
                        },
                        new
                        {
                            Id = 222,
                            Attack = 8,
                            Defence = 2,
                            Name = "Corporate Infrastructure Director"
                        },
                        new
                        {
                            Id = 223,
                            Attack = 5,
                            Defence = 10,
                            Name = "Customer Markets Strategist"
                        },
                        new
                        {
                            Id = 224,
                            Attack = 1,
                            Defence = 9,
                            Name = "Chief Accounts Developer"
                        },
                        new
                        {
                            Id = 225,
                            Attack = 10,
                            Defence = 5,
                            Name = "District Creative Strategist"
                        },
                        new
                        {
                            Id = 226,
                            Attack = 2,
                            Defence = 2,
                            Name = "National Directives Coordinator"
                        },
                        new
                        {
                            Id = 227,
                            Attack = 7,
                            Defence = 5,
                            Name = "Product Usability Director"
                        },
                        new
                        {
                            Id = 228,
                            Attack = 3,
                            Defence = 0,
                            Name = "Direct Web Executive"
                        },
                        new
                        {
                            Id = 229,
                            Attack = 5,
                            Defence = 2,
                            Name = "Human Accounts Supervisor"
                        },
                        new
                        {
                            Id = 230,
                            Attack = 3,
                            Defence = 0,
                            Name = "Forward Paradigm Assistant"
                        },
                        new
                        {
                            Id = 231,
                            Attack = 9,
                            Defence = 3,
                            Name = "Dynamic Program Strategist"
                        },
                        new
                        {
                            Id = 232,
                            Attack = 4,
                            Defence = 10,
                            Name = "Future Optimization Associate"
                        },
                        new
                        {
                            Id = 233,
                            Attack = 1,
                            Defence = 10,
                            Name = "Forward Tactics Orchestrator"
                        },
                        new
                        {
                            Id = 234,
                            Attack = 3,
                            Defence = 0,
                            Name = "Global Identity Agent"
                        },
                        new
                        {
                            Id = 235,
                            Attack = 4,
                            Defence = 2,
                            Name = "Investor Operations Architect"
                        },
                        new
                        {
                            Id = 236,
                            Attack = 10,
                            Defence = 6,
                            Name = "Direct Tactics Consultant"
                        },
                        new
                        {
                            Id = 237,
                            Attack = 5,
                            Defence = 5,
                            Name = "Lead Intranet Architect"
                        },
                        new
                        {
                            Id = 238,
                            Attack = 0,
                            Defence = 0,
                            Name = "Chief Mobility Supervisor"
                        },
                        new
                        {
                            Id = 239,
                            Attack = 6,
                            Defence = 0,
                            Name = "Investor Program Strategist"
                        },
                        new
                        {
                            Id = 240,
                            Attack = 2,
                            Defence = 7,
                            Name = "Future Accountability Producer"
                        },
                        new
                        {
                            Id = 241,
                            Attack = 3,
                            Defence = 3,
                            Name = "International Web Supervisor"
                        },
                        new
                        {
                            Id = 242,
                            Attack = 0,
                            Defence = 7,
                            Name = "National Communications Architect"
                        },
                        new
                        {
                            Id = 243,
                            Attack = 1,
                            Defence = 1,
                            Name = "District Markets Administrator"
                        },
                        new
                        {
                            Id = 244,
                            Attack = 3,
                            Defence = 8,
                            Name = "Lead Configuration Administrator"
                        },
                        new
                        {
                            Id = 245,
                            Attack = 8,
                            Defence = 5,
                            Name = "National Paradigm Representative"
                        },
                        new
                        {
                            Id = 246,
                            Attack = 0,
                            Defence = 3,
                            Name = "Future Marketing Developer"
                        },
                        new
                        {
                            Id = 247,
                            Attack = 1,
                            Defence = 10,
                            Name = "Senior Solutions Coordinator"
                        },
                        new
                        {
                            Id = 248,
                            Attack = 7,
                            Defence = 2,
                            Name = "District Division Executive"
                        },
                        new
                        {
                            Id = 249,
                            Attack = 0,
                            Defence = 7,
                            Name = "Human Directives Orchestrator"
                        },
                        new
                        {
                            Id = 250,
                            Attack = 2,
                            Defence = 9,
                            Name = "Direct Program Director"
                        },
                        new
                        {
                            Id = 251,
                            Attack = 6,
                            Defence = 0,
                            Name = "Dynamic Security Engineer"
                        },
                        new
                        {
                            Id = 252,
                            Attack = 1,
                            Defence = 8,
                            Name = "Senior Applications Coordinator"
                        },
                        new
                        {
                            Id = 253,
                            Attack = 9,
                            Defence = 5,
                            Name = "Product Functionality Administrator"
                        },
                        new
                        {
                            Id = 254,
                            Attack = 6,
                            Defence = 3,
                            Name = "Legacy Operations Agent"
                        },
                        new
                        {
                            Id = 255,
                            Attack = 6,
                            Defence = 9,
                            Name = "Central Interactions Director"
                        },
                        new
                        {
                            Id = 256,
                            Attack = 5,
                            Defence = 6,
                            Name = "National Branding Facilitator"
                        },
                        new
                        {
                            Id = 257,
                            Attack = 6,
                            Defence = 7,
                            Name = "Customer Intranet Technician"
                        },
                        new
                        {
                            Id = 258,
                            Attack = 10,
                            Defence = 6,
                            Name = "Regional Configuration Consultant"
                        },
                        new
                        {
                            Id = 259,
                            Attack = 9,
                            Defence = 0,
                            Name = "Forward Interactions Assistant"
                        },
                        new
                        {
                            Id = 260,
                            Attack = 2,
                            Defence = 3,
                            Name = "Forward Infrastructure Strategist"
                        },
                        new
                        {
                            Id = 261,
                            Attack = 10,
                            Defence = 4,
                            Name = "Forward Web Facilitator"
                        },
                        new
                        {
                            Id = 262,
                            Attack = 7,
                            Defence = 2,
                            Name = "Dynamic Factors Associate"
                        },
                        new
                        {
                            Id = 263,
                            Attack = 8,
                            Defence = 0,
                            Name = "Investor Group Facilitator"
                        },
                        new
                        {
                            Id = 264,
                            Attack = 10,
                            Defence = 6,
                            Name = "International Metrics Associate"
                        },
                        new
                        {
                            Id = 265,
                            Attack = 5,
                            Defence = 9,
                            Name = "Investor Optimization Planner"
                        },
                        new
                        {
                            Id = 266,
                            Attack = 1,
                            Defence = 9,
                            Name = "Senior Tactics Technician"
                        },
                        new
                        {
                            Id = 267,
                            Attack = 3,
                            Defence = 8,
                            Name = "District Interactions Facilitator"
                        },
                        new
                        {
                            Id = 268,
                            Attack = 4,
                            Defence = 10,
                            Name = "International Solutions Facilitator"
                        },
                        new
                        {
                            Id = 269,
                            Attack = 6,
                            Defence = 8,
                            Name = "Central Solutions Representative"
                        },
                        new
                        {
                            Id = 270,
                            Attack = 7,
                            Defence = 1,
                            Name = "National Creative Planner"
                        },
                        new
                        {
                            Id = 271,
                            Attack = 0,
                            Defence = 8,
                            Name = "Future Solutions Developer"
                        },
                        new
                        {
                            Id = 272,
                            Attack = 5,
                            Defence = 10,
                            Name = "Forward Configuration Technician"
                        },
                        new
                        {
                            Id = 273,
                            Attack = 4,
                            Defence = 0,
                            Name = "Direct Factors Orchestrator"
                        },
                        new
                        {
                            Id = 274,
                            Attack = 7,
                            Defence = 8,
                            Name = "National Research Executive"
                        },
                        new
                        {
                            Id = 275,
                            Attack = 7,
                            Defence = 6,
                            Name = "Chief Directives Orchestrator"
                        },
                        new
                        {
                            Id = 276,
                            Attack = 6,
                            Defence = 5,
                            Name = "Product Configuration Planner"
                        },
                        new
                        {
                            Id = 277,
                            Attack = 9,
                            Defence = 10,
                            Name = "Direct Optimization Officer"
                        },
                        new
                        {
                            Id = 278,
                            Attack = 6,
                            Defence = 3,
                            Name = "Principal Paradigm Strategist"
                        },
                        new
                        {
                            Id = 279,
                            Attack = 0,
                            Defence = 10,
                            Name = "Lead Research Agent"
                        },
                        new
                        {
                            Id = 280,
                            Attack = 5,
                            Defence = 7,
                            Name = "Investor Branding Facilitator"
                        },
                        new
                        {
                            Id = 281,
                            Attack = 8,
                            Defence = 9,
                            Name = "Human Brand Assistant"
                        },
                        new
                        {
                            Id = 282,
                            Attack = 0,
                            Defence = 8,
                            Name = "Forward Mobility Orchestrator"
                        },
                        new
                        {
                            Id = 283,
                            Attack = 0,
                            Defence = 2,
                            Name = "Dynamic Response Representative"
                        },
                        new
                        {
                            Id = 284,
                            Attack = 2,
                            Defence = 6,
                            Name = "Direct Paradigm Supervisor"
                        },
                        new
                        {
                            Id = 285,
                            Attack = 8,
                            Defence = 2,
                            Name = "Investor Research Agent"
                        },
                        new
                        {
                            Id = 286,
                            Attack = 8,
                            Defence = 10,
                            Name = "Investor Solutions Engineer"
                        },
                        new
                        {
                            Id = 287,
                            Attack = 5,
                            Defence = 9,
                            Name = "Product Web Developer"
                        },
                        new
                        {
                            Id = 288,
                            Attack = 2,
                            Defence = 9,
                            Name = "Central Configuration Agent"
                        },
                        new
                        {
                            Id = 289,
                            Attack = 9,
                            Defence = 0,
                            Name = "Investor Intranet Associate"
                        },
                        new
                        {
                            Id = 290,
                            Attack = 7,
                            Defence = 7,
                            Name = "National Implementation Engineer"
                        },
                        new
                        {
                            Id = 291,
                            Attack = 0,
                            Defence = 1,
                            Name = "Central Tactics Specialist"
                        },
                        new
                        {
                            Id = 292,
                            Attack = 1,
                            Defence = 3,
                            Name = "Product Infrastructure Supervisor"
                        },
                        new
                        {
                            Id = 293,
                            Attack = 3,
                            Defence = 3,
                            Name = "Human Usability Analyst"
                        },
                        new
                        {
                            Id = 294,
                            Attack = 9,
                            Defence = 1,
                            Name = "Human Solutions Associate"
                        },
                        new
                        {
                            Id = 295,
                            Attack = 10,
                            Defence = 5,
                            Name = "Corporate Brand Planner"
                        },
                        new
                        {
                            Id = 296,
                            Attack = 2,
                            Defence = 6,
                            Name = "Investor Accounts Coordinator"
                        },
                        new
                        {
                            Id = 297,
                            Attack = 7,
                            Defence = 3,
                            Name = "International Usability Specialist"
                        },
                        new
                        {
                            Id = 298,
                            Attack = 5,
                            Defence = 9,
                            Name = "Lead Accountability Manager"
                        },
                        new
                        {
                            Id = 299,
                            Attack = 2,
                            Defence = 10,
                            Name = "Internal Metrics Director"
                        },
                        new
                        {
                            Id = 300,
                            Attack = 2,
                            Defence = 2,
                            Name = "Dynamic Identity Liaison"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
